version: "3.8"
services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.14
    environment:
      - ALLOW_RESET=TRUE
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - "8000:8000"
  pg:
    image: ankane/pgvector:v0.5.1
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
volumes:
  index_data:
    driver: local